### ISSUE TITLE
Annotating/labelling genes

### ISSUE THREAD

**Issue by iwilkie** [robotoD/GenoVi#16]
Hi,

I've been using your tool for some time now to generate overviews of different genomes. I was wondering if there's a possibility to add custom labels/annotations to specific genes of interest?

For example to generate the GenoVi figure, but also label specific genes based on their locus/position?

Thanks in advance for answering the question, I love the tool and the work you have put into making it work smoothly! :)

**Comment by robotoD** [comment]
Hi iwilkie,

Sorry for the late answer
At the current version, GenoVi does not allow to add custom labels or annotations to highlight any part of the genome. In the next versions of the tool we will add this option, many users had asked for the same option.

Thank you for your feedback, if you have any other ideas or comments please do not hesitate to reach us.
